version: '3.8'

services:
  mysql_test_book_house_auth:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test_book_house_auth
      MYSQL_ROOT_PASSWORD: root

  mysql_book_house_auth:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: book_house_auth
      MYSQL_ROOT_PASSWORD: root

  mysql_test_book_house_credit_card:
    image: mysql:latest
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: test_book_house_credit_card
      MYSQL_ROOT_PASSWORD: root

  mysql_book_house_credit_card:
    image: mysql:latest
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: book_house_credit_card
      MYSQL_ROOT_PASSWORD: root

  mysql_test_book_house_order:
    image: mysql:latest
    ports:
      - "3311:3306"
    environment:
      MYSQL_DATABASE: test_book_house_order
      MYSQL_ROOT_PASSWORD: root

  mysql_book_house_credit_order:
    image: mysql:latest
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: book_house_order
      MYSQL_ROOT_PASSWORD: root

  mysql_test_book_house_product:
    image: mysql:latest
    ports:
      - "3313:3306"
    environment:
      MYSQL_DATABASE: test_book_house_product
      MYSQL_ROOT_PASSWORD: root

  mysql_book_house_product:
    image: mysql:latest
    ports:
      - "3314:3306"
    environment:
      MYSQL_DATABASE: book_house_product
      MYSQL_ROOT_PASSWORD: root